### ISSUE TITLE
Damageincoming GetPlayerInfoByGUID error

### ISSUE THREAD

**Issue by Tonyleila** [dandruff/xCT#100]
Got this error, sorry only have a screenshot of it
http://i.imgur.com/VXtNWyv.jpg

**Comment by Cimplex** [comment]
I have also been seeing this. You turned on Player Names in the name settings?

Somehow, there is a combination of a sourceFlags reporting that a player is doing damage to you, but the event has a creature GUID, not a player... It's weird but I got it to blow up on the second boss in Halls of Valor when people hit the light orbs on mythic difficulty.

Haven't seen it happen in Nelth's "Hort" yet. Probably what gonna have to happen is more logging on my part to get it fixed because I have been trying :(. If anything try the latest commit, should be stable enough.

**Comment by Tonyleila** [comment]
> You turned on Player Names in the name settings?
yep

Lets see if I get this error again I'll report here :)
