### ISSUE TITLE
xCT+ Hunter Volley merge 

### ISSUE THREAD

**Issue by Boczaa** [dandruff/xCT#226]
Is there any way to merge volley hits ? I can't find any way to do it.
(spell merger is active)

**Comment by Boczaa** [comment]
bypassed it by limiting outgoing damage to show only 5k +. 
But now i noticed wailing arrow has the same problem

**Comment by thematrixincendies** [comment]
This is so easy to add yourself.
Go to [this](https://github.com/dandruff/xCT/blob/a4d6938a4d81928cf943efa312d6663661acd7f1/config/merge_class.lua#L197) file and add the spell id below the correct "spec" line in the format:
```lua
spell '<id>' '<timeout>'
```
Replace <id> with the spell id and <timeout> with the time the merger is supposed to wait for a second hit. If it's an AOE spell, just use timeout 0.5, if it ticks or is channeled you need to set it to a value you like. If a spell does repeated damage for 3 seconds for example, you could set it to 3.5, but that also results in xCT not showing you any damage for 3.5s, because it waits for a merge.

**Comment by RedAces** [comment]
Added to https://github.com/dandruff/xCT/pull/236
