### ISSUE TITLE
Broken standard combat text

### ISSUE THREAD

**Issue by DarkyAngel83** [dandruff/xCT#229]
Went to use the addon didn't get on with it nothing personal went to uninstall it now it wont allow me to use my standard blizzard combat text I have nothing why what's the addon done to my game I have scan and repaired the game my settings are not changed what's going on ???

**Comment by Cimplex** [comment]
It’s because xct+ changes cvars, and they get saved by the wow client. You need to reset them back to defaults. There might be a couple ways to do this:

1. AdvancedInterfaceOptions add on might be able to help you see which ones are not default
2. Deleting the Config.wtf file (I think it’s somewhere in the interface folder)
