### ISSUE TITLE
[Bug]: Paladin Spam Filter Additions

### ISSUE THREAD

**Issue by Retjesir** [dandruff/xCT#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### WoW version

10.2.7.54762

### xCT+ version

4.7.2

### What happened?

Spam merger isn't picking up a few abilities for Paladin.

A few spells aren't rolling up into a total (ex. 163k  x4)

I think the reason for this is the spellIDs in the Class Spells tab don't match the current spell ids.

Wake of Ashes says it is 204273 in XCT, my tooltip has it being 255937
Blade of Justice is not found in XCT, but should be 184575
Final Reckoning is not present in XCT, but it should be 343721
Divine Toll is not present in XCT, it should be 375576
Searing Light is not present in XCT, I think it is 404540

Even Templar's Verdict doesn't have the same spellID. 
![Screenshot 2024-05-18 213116](https://github.com/dandruff/xCT/assets/170218606/b7cf5014-5824-4dc5-bef3-92698b7ba82e)
![Screenshot 2024-05-18 214512](https://github.com/dandruff/xCT/assets/170218606/d6f0053b-c0d0-4518-a735-14a74299797f)

**Comment by Cimplex** [comment]
So it looks like you are giving me the tooltips for the talents themselves and not the triggered spell IDs.

The easiest way to get the actual spell IDs is to enable the Show Spell ID's option (I believe its in the Spell/Spam Merger section). Once you do that, trigger these spells again, on something like a target dummy and see which ID's you get.

I just mention this, because WoW does generally have two (or more) spell ID's depending on lots of things, such as having a talent that modifies the ability. If we look at the spell ID you gave me [Wake of Ashes](https://www.wowhead.com/spell=255937/wake-of-ashes), it does mention that it is a talent and that it triggers several other spells.
