### ISSUE TITLE
Scourge Strike Merge Issue

### ISSUE THREAD

**Issue by Derponastick** [dandruff/xCT#76]
There is a poblem I'm having with Scourge Strike, crit merger is fine, all multistrike mergers as well as the necrosis procs that happen off of my Scourge multistrike are all fine. 

My issue is this: Scourge Strike has 2 damage portions, a physical half, and a shadow half. I'd like to find out (or request if this isn't available) if it is at all possible to combine Scourge Strike's physical and shadow halves into one ability that shows up on my outgoing feed, so that Scourge Strike on my outgoing includes: The physical half (and its multistrikes), and the shadow half (and its multistrikes). Would be kind of cool to have one scourge icon with like 4 small multistrike icons to the side, I really want to know just how much damage a single scourge strike actually does collectively and there does not seem to be an addon to show that out there right now. This was mostly the reason I got the addon in the first place :P.

Many thanks in advance!

**Comment by Cimplex** [comment]
So here is the problem. xCT+ was only made to show 2 multistrike events per original event. You could attempt to merge both Scourge Strikes together, but this might have unforseen consequences. In order to do this, you need to figure out the two spell IDs for the spell:

Then take a look at this [config file](https://github.com/dandruff/xCT/blob/8d3a2c8c18489b52443ee26417eda1a6b9df2d4d/config/merge.lua#L367) (xCT+/config/merge.lua : Line 367) and add the two spells ID's there:
    
    [spell_id1] = [spell_id2],
    
Let me know if you need anymore help or if it doesn't work, we might be able to figure something else out.

**Comment by behub** [comment]
Can most likely close this now as when i went over all the new legion spells i did the merger for this.

**Comment by Derponastick** [comment]
Yes you helped wonders for the while MS lasted you can close it now ! :)

Sent from my iPhone

On 20 Aug 2016, at 14:59, behub (torch) <notifications@github.com<mailto:notifications@github.com>> wrote:


Can most likely close this now as when i went over all the new legion spells i did the merger for this.

-
